---
title: "K-means"
author: "Benson"
date: "1/22/2022"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(tidymodels)
library(tidytext)
library(tidycharts)
```

## Loading the data
```{r}
library(readr)
employed<- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2021/2021-02-23/employed.csv")
View(employed)
```


## Explore the data
```{r}
employed_tidy<-employed %>%
  filter(!is.na(employ_n)) %>%
  group_by(occupation = paste(industry,minor_occupation),
           race_gender) %>% 
  summarise(n = mean(employ_n)) %>% 
  ungroup()
```

```{r}

employed_tidy %>% 
  filter(race_gender== "TOTAL")



employed_tidy %>% 
  filter(race_gender %in% c("women","Black or African American","Asian")) %>% 
  pivot_wider(names_from = race_gender,values_from = n,values_fill = 0) %>% 
  janitor::clean_names() %>% 
  left_join(employed_tidy %>% 
              filter(race_gender == "TOTAL") %>% 
              select(-race_gender) %>% 
              rename(total = n)) %>% 
  filter(total>1e4) %>% 
  mutate(across(c(asian,black_or_african_american,women), ~ . / total),total = log(total))
```

 
 